---
- hosts: lb
  become: yes
  roles:
    - { role: nginx, when: enable_nginx_lb == false and load_balancer_is_required == false }
    - { role: apache, when: enable_apache_lb == true and load_balancer_is_required == true }