---
# tasks file for php
- name: Install php dependencies
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
      - zip
      - libapache2-mod-php
      - phploc
      - php-xml
      - php-bcmath
      - php-bz2
      - php-intl
      - php-gd
      - php-mbstring
      - php-mysql
      - php-zip
