---
  - hosts: all
    - import_playbook: /static-assignments/common.yml
    - import_playbook: ../static-assignments/common-del.yml

  - hosts: webservers
    - import_playbook: ../static-assignments/webservers.yml